---
title: Funemployed – say no to the nine to five.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: 'profiles'
    type: Profiles
  values:
    Achievements:
    - ''
    Website: 
    Twitter: 
    Facebook: 
    Instagram: 
    Snapchat: 
    YouTube: 
    Twitch: 
    LinkedIn: 
    Pinterest: 
    Medium: 
email: hello@matthewvernon.co
description: Stories from freelancers, influencers, nomads, streamers, bloggers and
  vloggers about how they got their start, how they live their lives and how they
  make their money.
baseurl: 
url: 
twitter_username: funemployed
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
