---
title: Funemployed – say no to the nine to five.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  profiles:
    title: Profiles
    output: true
  uploads:
    title: Uploads
    output: true

email: hello@matthewvernon.co
description: Stories from freelancers, influencers, nomads, streamers, bloggers and
  vloggers about how they got their start, how they live their lives and how they
  make their money.
baseurl: 
url: 
twitter_username: funemployed
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

defaults:
  - scope:
      type: "Profiles"
    values:
        Excerpt: "* Day in the life content"
        Blurb: Blurb for profile card goes here
        Achievements:
        - "\U0001F1FA\U0001F1F8 Born and raised in Texas"
        Profile Image: "/uploads/profileimg.png"
        Website: 
        Twitter: 
        Facebook: 
        Instagram: 
        Snapchat: 
        YouTube: 
        Twitch: 
        LinkedIn: 
        Pinterest: 
        Medium:
